name: spiderfoot
base: core22
adopt-info: spiderfoot
summary: SpiderFoot is an open source intelligence (OSINT) automation tool.
description: |
  SpiderFoot is an open source intelligence (OSINT) automation tool. It integrates with just about every data source available and utilises a range of methods for data analysis, making that data easy to navigate.

  SpiderFoot has an embedded web-server for providing a clean and intuitive web-based interface but can also be used completely via the command-line.

  **FEATURES**

    * Web based UI or CLI
    * Over 200 modules (see below)
    * Python 3.7+
    * YAML-configurable correlation engine with 37 pre-defined rules
    * CSV/JSON/GEXF export
    * API key export/import
    * SQLite back-end for custom querying
    * Highly configurable
    * Fully documented
    * Visualisations
    * TOR integration for dark web searching
    * Dockerfile for Docker-based deployments
    * Can call other tools like DNSTwist, Whatweb, Nmap and CMSeeK

  Documentation:- https://www.spiderfoot.net/documentation

  Asciinema videos:- https://asciinema.org/~spiderfoot
  
  To use `nmap` in SpiderFoot, you've to manually connect two interfaces with the following commands:-
  
  `snap connect spiderfoot:nmap nmap:nmap`
  
  `snap connect nmap:network-control`

grade: stable
confinement: strict
#compression: lzo

icon: sf.png

environment:
  LANG: C.UTF-8
  LC_ALL: C.UTF-8
  LD_LIBRARY_PATH: $LD_LIBRARY_PATH:$SNAP/lib:$SNAP/usr/lib/$CRAFT_ARCH_TRIPLET:$SNAP/usr/lib/$CRAFT_ARCH_TRIPLET/blas

plugs:
  nmap:
    interface: content
    target: $SNAP
    default-provider: nmap
    
architectures:
  - build-on: amd64
  - build-on: arm64
  - build-on: armhf
  - build-on: ppc64el
  - build-on: s390x


apps:
  spiderfoot:
    command: bin/snapcraft-preload $SNAP/SpiderFoot
    plugs: [home, network, network-bind]

  cli:
    command: bin/snapcraft-preload $SNAP/sfcli.py
    plugs: [home, network, network-bind]


parts:

  dnstwist:
    source: https://github.com/elceef/dnstwist.git
    plugin: python

    override-build: |
      craftctl default
      find $CRAFT_PART_INSTALL/ -name "*.pyc" -exec rm -rf {} +

    stage:
      - -bin/activate*
      - -lib/python3.10/site-packages/wheel*
      - -lib/python3.10/site-packages/pip*
      - -lib/python3.10/site-packages/setuptools*
      - -pyvenv.cfg

  snapcraft-preload:
    source: https://github.com/sergiusens/snapcraft-preload.git
    plugin: cmake
    build-packages:
      - on amd64:
        - gcc-multilib
        - g++-multilib
        
  spiderfoot:
    after: [snapcraft-preload]
    plugin: python
    source: https://github.com/smicallef/spiderfoot.git
    build-packages:
      - libxml2-dev
      - libxslt1-dev
      - libffi-dev
      - libssl-dev
      - libjpeg-dev
      - rustc
      - cargo

    override-build: |
      craftctl default
      pip install -r requirements.txt
      rm *ocker* *.md *.txt
      sed -i 's#consider adding authentication to protect this instance!#add passwd file in $HOME/snap/spiderfoot/current/.spiderfoot#g' sf.py
      cp sf.py SpiderFoot
      cp -r ./* $CRAFT_PART_INSTALL/
      craftctl set version=$(git describe)

    override-prime: |
      craftctl default
      mv usr/local/bin/snapcraft-preload bin/
      mv usr/local/lib/lib* lib/
      rm -rf usr/

    prime:
      - -share/python-wheels
      - -lib/python3.10/site-packages/pip*
      - -lib/python3.10/site-packages/setuptools*
